stages:
  - test
  - build
  - deploy

test:
  image: python:3.9
  stage: test

  services:
    - postgres

  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /hotfix/

  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    PIPENV_CACHE_DIR: $CI_PROJECT_DIR/.cache/pipenv
    PIP_DOWNLOAD_CACHE: $CI_PROJECT_DIR/.cache/pip_download_cache
    ENV_FOR_DYNACONF: test

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .cache

  coverage: '/TOTAL.*\s+(\d+%)$/'

  before_script:
    - pip install .[test]

  script:
    #  - pip install black --upgrade
    #  - python -m unittest -v
    - coverage run -m pytest
    #  - black -S -l 80 --check --diff ./
    - coverage report -m --skip-covered

build models:
  image: python:3.7
  stage: build
  only:
    - master
  before_script:
    - pip install twine setuptools wheel
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: $CI_JOB_TOKEN
  script:
    - python setup_models.py sdist bdist_wheel
    - python -m twine upload --verbose --repository-url https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
